version: "3.3"
services:
  backend:
    image: backend
    build:
      context: backend/
    volumes:
      - "game-data:/app/games"

  frontend:
    image: frontend
    build:
      context: frontend/
    ports:
      - 8000:80

volumes:
  game-data: